# Generated by Django 2.1.15 on 2020-02-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20200203_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databaseconfig',
            old_name='username',
            new_name='owner',
        ),
    ]
