# Generated by Django 2.1.15 on 2020-02-03 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20200203_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconfig',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_databases', to=settings.AUTH_USER_MODEL),
        ),
    ]
