# Generated by Django 2.1.15 on 2020-02-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20200203_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconfig',
            name='display_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
